networks:
  mynetwork:
    driver: bridge

services:
  email-microservice:
    build: ./Email_Microservice
    image: email-microservice
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: sqlite:////app_parent/data/email.db
    volumes:
      - ./Email_Microservice/..:/app_parent
    networks:
      - mynetwork

  user-authentication-microservice:
    build: ./User_Authentication_Microservice
    image: user-authentication-microservice
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: auth_app.py
      FLASK_ENV: development
      DATABASE_URL: sqlite:////app_parent/data/auth.db
    volumes:
      - ./User_Authentication_Microservice/..:/app_parent
    networks:
      - mynetwork

  event-check-in-microservice:
    build: ./Event_Check_In_Microservice
    image: event-check-in-microservice
    ports:
      - "5003:5003"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: sqlite:////app_parent/data/checkin.db
    volumes:
      - ./Event_Check_In_Microservice/..:/app_parent
    networks:
      - mynetwork

  media-management-microservice:
    build: ./Media_Management_Microservice
    image: media-management-microservice
    ports:
      - "5004:5004"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: sqlite:////app_parent/data/media.db
    volumes:
      - ./Media_Management_Microservice/..:/app_parent
    networks:
      - mynetwork

  review-and-feedback-microservice:
    build: ./Review-And-Feedback-Microservice
    image: review-and-feedback-microservice
    ports:
      - "5005:5005"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./Review-And-Feedback-Microservice/..:/app_parent
    networks:
      - mynetwork

  server:
    build: ./Server
    image: server
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: server.py
      FLASK_ENV: development
      DATABASE_URL: sqlite:////app_parent/data/events.db
    volumes:
      - ./Server/..:/app_parent
    networks:
      - mynetwork